# SMTP Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Email credentials
mail.username=lephongle475@gmail.com
mail.password=skinmocovqpmworm

# Email settings
mail.from=lephongle475@gmail.com
mail.from.name=gmail